//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoffeShopApp.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Product
    {
        private string name;
        private double price;
        private double qty;

        public Product()
        {

        }
        public Product(string name, double price, double qty)
            {
            Name = name;
            Price = price;
            Qty = qty;
            }
        public string Name { get; set; }
        public double Price { get; set; }
        public double Qty { get; set; }
    }
}
